#! /usr/bin/env python
#
# E. Jeschke
# R. Kackley
#

# Standard library imports
import sys, os
from argparse import ArgumentParser

from g2base import ssdlog

from integgui2.main import main

if __name__ == '__main__':

    argprs = ArgumentParser(description="The integrated GUI observation controller")

    argprs.add_argument("--debug", dest="debug", default=False,
                        action="store_true",
                        help="Enter the pdb debugger on main()")
##     argprs.add_argument("-c", "--channels", dest="channels", default='g2task',
##                       metavar="LIST",
##                       help="Subscribe to the comma-separated LIST of channels")
    argprs.add_argument("--display", dest="display", metavar="HOST:N",
                        help="Use X display on HOST:N")
    argprs.add_argument("--fitsdir", dest="fitsdir",
                        metavar="DIR",
                        help="Specify DIR to look for FITS files")
    argprs.add_argument("-g", "--geometry", dest="geometry",
                        metavar="GEOM", default="1860x1100+57+0",
                        help="X geometry for initial size and placement")
    argprs.add_argument("-i", "--inst", dest="instrument",
                        help="Specify instrument(s) to use for integgui")
    argprs.add_argument("-m", "--monitor", dest="monitor", default='monitor',
                        metavar="NAME",
                        help="Subscribe to feeds from monitor service NAME")
    argprs.add_argument("--monname", dest="monname", metavar="NAME",
                        help="Use NAME as our monitor subscriber name")
    argprs.add_argument("-p", "--path", dest="monpath", default='mon.sktask',
                        metavar="PATH",
                        help="Show values for PATH in monitor")
    argprs.add_argument("--monport", dest="monport", type=int, default=10017,
                        help="Register monitor using PORT", metavar="PORT")
    argprs.add_argument("--numthreads", dest="numthreads", type=int,
                        default=50,
                        help="Start NUM threads in thread pool", metavar="NUM")
    argprs.add_argument("--port", dest="port", type=int, default=12050,
                        help="Register using PORT", metavar="PORT")
    argprs.add_argument("--profile", dest="profile", action="store_true",
                        default=False,
                        help="Run the profiler on main()")
    argprs.add_argument("--session", dest="session", metavar="NAME",
                        default='main',
                        help="Configure from session NAME")
    argprs.add_argument("--svcname", dest="svcname", metavar="NAME",
                        default="integgui0",
                        help="Register using NAME as service name")
    argprs.add_argument("--taskmgr", dest="taskmgr", metavar="NAME",
                        default='taskmgr0',
                        help="Connect to TaskManager with name NAME")
    ssdlog.addlogopts(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

##     if len(args) != 0:
##         argprs.error("incorrect number of arguments")

    if options.display:
        os.environ['DISPLAY'] = options.display

    main(options, args)
